version: '3'
services:

  transactiondb-i:
    build:
      context: ./src/db
      dockerfile: dockerfile
    container_name: transactiondb-c
    networks:
      - transactionms-network
    ports:
      - "3006:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "transactiondb-c"]
      timeout: 20s
      retries: 10

  transactionms-i:
    build:
      context: .
      dockerfile: dockerfile
    container_name: transactionms-c
    networks:
      - transactionms-network
    ports:
      - "3003:3003"
    depends_on:
      transactiondb-i:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3001/health-check || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  transactionms-network: