apiVersion: apps/v1
kind: Deployment
metadata:
  name: transationdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactiondb
  template:
    metadata:
      labels:
        app: transactiondb
    spec:
      containers:
      - name: transactiondb-c
        image: docker.io/nitishbits/transactiondb-i:latest
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: transactiondb-service
spec:
  selector:
    app: transactiondb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
