apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactionms
  template:
    metadata:
      labels:
        app: transactionms
    spec:
      containers:
      - name: transactionms-container
        image: docker.io/nitishbits/transactionms-i:latest
        ports:
        - containerPort: 3003
        readinessProbe:
          httpGet:
            path: /health-check
            port: 3003
          initialDelaySeconds: 20
          periodSeconds: 30
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: transactionms-service
spec:
  selector:
    app: transactionms
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: NodePort
  selector:
    app: transactionms
